[build]
  command = "npm run build && echo 'Build completed successfully'"
  publish = ".next"

[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"
  SECRETS_SCAN_OMIT_KEYS = "NODE_ENV,MONGODB_URI"

# Redirect API routes to Netlify functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  directory = "netlify/functions"

[functions."*"]
  timeout = "30s"
