[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  # Directory for Netlify functions
  directory = "netlify/functions"

[functions."*"]
  # Increase function timeout for Document AI processing (max 30s for free tier)
  timeout = "30s"